create table fuze.orcamentos(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  DataOrcamento  DATE DEFAULT NULL,
  agencia_id INT UNSIGNED DEFAULT NULL,
  cliente_id INT UNSIGNED DEFAULT NULL,
  pracas VARCHAR(45) DEFAULT NULL,
  midias VARCHAR(45) DEFAULT NULL,
  periodoDeUso VARCHAR(45) DEFAULT NULL,
  ac VARCHAR(45) DEFAULT NULL,
  job VARCHAR(45) DEFAULT NULL,
  socio_id INT UNSIGNED DEFAULT NULL,
  descricao VARCHAR(65) NOT NULL,
  prazoExecucao VARCHAR(45) DEFAULT NULL,
  mostrarRodape TINYINT(1) UNSIGNED DEFAULT '0',
  dias INT UNSIGNED DEFAULT 0,
  temBV TINYINT(1) UNSIGNED DEFAULT '0',
  temNF TINYINT(1) UNSIGNED DEFAULT '0',
  ajuste DECIMAL(15,2) DEFAULT 0,
  tipo TINYINT(2) ,
  primary key (id),
  KEY fk_orcamento_agencias (agencia_id),
  KEY fk_orcamento_clientes (cliente_id),
  KEY fk_orcamento_socios (socio_id),
  constraint fk_orcamento_agencias foreign key (agencia_id) references fuze.agencias (id) on update restrict on delete restrict,
   constraint fk_orcamento_clientes foreign key (cliente_id) references fuze.clientes (id) on update restrict on delete restrict,
   constraint fk_orcamento_socios foreign key (socio_id) references fuze.socios (id) on update restrict on delete restrict
 )ENGINE=InnoDB CHARSET=latin1;